char[][] level0 = {
  "X          X".toCharArray(),
  "X          X".toCharArray(),
  "X          X".toCharArray(),
  "X          X".toCharArray(),
  "X          X".toCharArray(),
  "X          X".toCharArray(),
  "X          X".toCharArray(),
  "X          X".toCharArray(),
  "X          X".toCharArray(),
  "X          X".toCharArray(),
  "X          X".toCharArray(),
  "X          X".toCharArray(),
  "X          X".toCharArray(),
  "X          X".toCharArray(),
  "X          X".toCharArray(),
  "X          X".toCharArray(),
  "X          X".toCharArray(),
  "X          X".toCharArray(),
  "X          X".toCharArray(),
  "X          X".toCharArray(),
  "XXXXXXXXXXXX".toCharArray(),
};

char[][] level1 = {
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                           G  X".toCharArray(),
"X                                                      XXXXXXXXX".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX".toCharArray(),
};

char[][] level2 = {
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                 G            X".toCharArray(),
"X                                         XXXXXXXXX            X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                             XXXXXXXX                         X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                         XXXXXXXXX            X".toCharArray(),
"X                     X                                        X".toCharArray(),
"X                     X                                        X".toCharArray(),
"X                     X                                        X".toCharArray(),
"X                     X                                        X".toCharArray(),
"X                     X                                        X".toCharArray(),
"X       X             X                                        X".toCharArray(),
"X       X             X                                        X".toCharArray(),
"X       X             X                                        X".toCharArray(),
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX".toCharArray()
};

char[][][] levels = {
    level0,
    level1,
    level2
};
        
