char[][] level1 = {
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                           G  X".toCharArray(),
"X                                                      XXXXXXXXX".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X       G                                                      X".toCharArray(),
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX".toCharArray(),
};

char[][] level2 = {
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                           G  X".toCharArray(),
"X                                                      XXXXXXXXX".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                 G                                            X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"XXXXX   XXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX".toCharArray(),
"XXXXXXX                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX".toCharArray(),
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX".toCharArray(),
};

char[][] level3 = {
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                 G            X".toCharArray(),
"X                                         XXXXXXXXX            X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                             XXXXXXXX                         X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                                              X".toCharArray(),
"X                                         XXXXXXXXX            X".toCharArray(),
"X                     X                                        X".toCharArray(),
"X                     X                                        X".toCharArray(),
"X                     X                                        X".toCharArray(),
"X                     X                                        X".toCharArray(),
"X                     X                                        X".toCharArray(),
"X       X             X                                        X".toCharArray(),
"X       X             X                                        X".toCharArray(),
"X       X             X                                        X".toCharArray(),
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX".toCharArray()
};

char[][][] levels = {
    level1,
    level2,
    level3
};
        
